### ISSUE TITLE
New mutations is an overestimate

### ISSUE THREAD

**Issue by jackkamm** [czbiohub/sc2-msspe-bioinfo#13]
Currently, we're counting any mutation different from the nearest sequence as a new mutation.

This doesn't correctly handle the case where the mutation happened on the nearest sequence instead of our sequence.

A better approach would be align both sequences to the ref, and only call new mutants when the nearest sequence is REF and the new sequence is ALT.

Note this would still not be totally correct -- it's possible for ALT to be the ancestral allele. But in practice, it should almost always be correct, especially if the new sequence is recent, and `--blast_sequences` is large enough.

The most correct thing to do would be to use the tree to infer the ancestral allele, but this would add a lot of code complexity and probably not worth it.

**Comment by batson** [comment]
Ancestral states are already being inferred by the `augur` pipeline.  The `auspice` JSON contains a tree with inferred mutations on each branch. Can trace back through the tree from all reference sequence leaves, and drop those branches. Mark all mutations on remaining branches as new.

**Comment by batson** [comment]
I have implemented the above (using @evogytis 's lovely Baltic framework).

![download](https://user-images.githubusercontent.com/1261162/79522752-607fa980-8011-11ea-9bd0-dd2b44739964.png)

gist here: https://gist.github.com/batson/4cc632b6a9ea7fc313d998bc1cf3ee71

Not sure where such code should go for this framework, but i'm happy to run on whatever samples you need for this week's paper.

**Comment by jackkamm** [comment]
Right now we're computing this stat in the `computeStats` process and `alignment_assembly_stats.py`, but it's upstream of the optional nextstrain step. It includes QC stats like depth of coverage, number of properly paired, that shouldn't depend on the phylogenetics. I think we should split up `computeStats` into 2 processes, for basic QC stats and for analysis stats, and then use the ancestral allele inference in the latter. In the near future, we should consider splitting the pipeline into separate ones for assembly and inference.

**Comment by batson** [comment]
Integrated in the refactor.
